---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elasticstack
  name: elasticsearch-master-config
  labels:
    app: elasticsearch
    role: master
data:
  elasticsearch.yml: |-
    cluster.name: docker-cluster
    node.name: elasticsearch-master
    discovery.seed_hosts: ["elasticsearch-master", "elasticsearch-data", "elasticsearch-client"]
    cluster.initial_master_nodes: ["elasticsearch-master"]
    network.host: 0.0.0.0
    node:
      master: true
      data: false
      ingest: false

    xpack.security.enabled: true
    xpack.monitoring.collection.enabled: true
---
